Fix the flaky SparkKMeans test
- Move static methods/variables to companion object
  - This reduce the serialization scope, which is causing issue
    - There is some ArrayList instance deep inside the serialization tree that causing concurrent modification issue (race condition).
    - This maybe a bug in Spark, nevertheless, reducing the closure scope helps.

It fixes this failure

http://builds.cask.co/browse/CDAP-DUT-1241/test

java.lang.AssertionError: expected:<200> but was:<204>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at co.cask.cdap.examples.sparkkmeans.SparkKMeansAppTest.requestService(SparkKMeansAppTest.java:97)
	at co.cask.cdap.examples.sparkkmeans.SparkKMeansAppTest.test(SparkKMeansAppTest.java:77)